### ISSUE TITLE
String index out of range: 2

### ISSUE THREAD

**Issue by liayn** [pbyrne84/DynamicReturnTypePlugin#46]
```
String index out of range: 2
java.lang.StringIndexOutOfBoundsException: String index out of range: 2
	at java.lang.String.substring(String.java:1907)
	at kotlin.KotlinPackage$StringsJVM$f9e19313.substring(StringsJVM.kt:42)
	at kotlin.KotlinPackage.substring(Unknown Source)
	at com.ptby.dynamicreturntypeplugin.signature_processingv2.SingleCallSignatureProcessor.getParameterFormatterForSignature(SingleCallSignatureProcessor.kt:19)
	at com.ptby.dynamicreturntypeplugin.signature_processingv2.ChainedSignatureProcessor.parseSignature(ChainedSignatureProcessor.kt:31)
	at com.ptby.dynamicreturntypeplugin.signature_processingv2.GetBySignature.getBySignature(GetBySignature.kt:39)
	at com.ptby.dynamicreturntypeplugin.DynamicReturnTypeProvider.getBySignature(DynamicReturnTypeProvider.kt:110)
...
```

code piece I wrote:
`$repo = GeneralUtility::makeInstance();`

.json used:
https://git.typo3.org/Packages/TYPO3.CMS.git/blob_plain/HEAD:/dynamicReturnTypeMeta.json

PHPStorm 8.0.3
Plugin-Version: 2.0.1

**Comment by pbyrne84** [comment]
Are you using a build above 141.1619 and are you still having this issue?

**Comment by liayn** [comment]
I'm on build 141.2461 and not an issue here anymore. Thanks for pinging me.
