### ISSUE TITLE
_parameterValueFormatter is being thrown in new version

### ISSUE THREAD

**Issue by pbyrne84** [pbyrne84/DynamicReturnTypePlugin#58]
_parameterValueFormatter cannot be null
java.lang.RuntimeException: _parameterValueFormatter cannot be null
	at com.ptby.dynamicreturntypeplugin.signature_processingv2.ChainedSignatureProcessor$FunctionConfiguration.parameterValueFormatter(ChainedSignatureProcessor.kt:95)
	at com.ptby.dynamicreturntypeplugin.signature_processingv2.SingleCallSignatureProcessor.processFunction(SingleCallSignatureProcessor.kt:62)
	at com.ptby.dynamicreturntypeplugin.signature_processingv2.SingleCallSignatureProcessor.getParameterFormatterForSignature(SingleCallSignatureProcessor.kt:20)
	at com.ptby.dynamicreturntypeplugin.signature_processingv2.ChainedSignatureProcessor.parseSignature(ChainedSignatureProcessor.kt:27)
	at com.ptby.dynamicreturntypeplugin.signature_processingv2.GetBySignature.getBySignature(GetBySignature.kt:24)
	at com.ptby.dynamicreturntypeplugin.DynamicReturnTypeProvider.getBySignature(DynamicReturnTypeProvider.kt:95)
	at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:416)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:302)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:79)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.global(PhpType.java:420)
	at com.jetbrains.php.lang.inspections.PhpVoidFunctionResultUsedInspection.analyzeCall(PhpVoidFunctionResultUsedInspection.java:49)
	at com.jetbrains.php.lang.inspections.PhpVoidFunctionResultUsedInspection.access$000(PhpVoidFunctionResultUsedInspection.java:23)
	at com.jetbrains.php.lang.inspections.PhpVoidFunctionResultUsedInspection$1.visitPhpFunctionCall(PhpVoidFunctionResultUsedInspection.java:35)
	at com.jetbrains.php.lang.psi.elements.impl.FunctionReferenceImpl.accept(FunctionReferenceImpl.java:36)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:69)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:294)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$200(LocalInspectionsPass.java:73)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:261)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:256)
	at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:128)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:112)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:88)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)

java.lang.RuntimeException: _parameterValueFormatter cannot be null
	at com.ptby.dynamicreturntypeplugin.signature_processingv2.ChainedSignatureProcessor$FunctionConfiguration.parameterValueFormatter(ChainedSignatureProcessor.kt:95)
	at com.ptby.dynamicreturntypeplugin.signature_processingv2.SingleCallSignatureProcessor.processFunction(SingleCallSignatureProcessor.kt:62)
	at com.ptby.dynamicreturntypeplugin.signature_processingv2.SingleCallSignatureProcessor.getParameterFormatterForSignature(SingleCallSignatureProcessor.kt:20)
	at com.ptby.dynamicreturntypeplugin.signature_processingv2.ChainedSignatureProcessor.parseSignature(ChainedSignatureProcessor.kt:27)
	at com.ptby.dynamicreturntypeplugin.signature_processingv2.GetBySignature.getBySignature(GetBySignature.kt:24)
	at com.ptby.dynamicreturntypeplugin.DynamicReturnTypeProvider.getBySignature(DynamicReturnTypeProvider.kt:95)
	at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:416)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:302)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:79)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.global(PhpType.java:420)
	at com.jetbrains.php.lang.inspections.PhpVoidFunctionResultUsedInspection.analyzeCall(PhpVoidFunctionResultUsedInspection.java:49)
	at com.jetbrains.php.lang.inspections.PhpVoidFunctionResultUsedInspection.access$000(PhpVoidFunctionResultUsedInspection.java:23)
	at com.jetbrains.php.lang.inspections.PhpVoidFunctionResultUsedInspection$1.visitPhpFunctionCall(PhpVoidFunctionResultUsedInspection.java:35)
	at com.jetbrains.php.lang.psi.elements.impl.FunctionReferenceImpl.accept(FunctionReferenceImpl.java:36)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:69)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:294)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$200(LocalInspectionsPass.java:73)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:261)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:256)
	at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:128)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:112)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:88)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)

**Comment by pbyrne84** [comment]
This seems to be to do with how functions are aliased back to global namespace as they do not defer back now

**Comment by pbyrne84** [comment]
Interestingly this may be a global problem with custom global functions
